# Generated by Django 3.0.6 on 2020-05-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookid', models.CharField(blank=True, max_length=1000, null=True)),
                ('gmailid', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonetype', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('notification', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('kilo', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('btype', models.IntegerField(blank=True, null=True)),
                ('usertype', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=1000, null=True)),
                ('place', models.CharField(blank=True, max_length=1000, null=True)),
                ('traindayinweek', models.CharField(blank=True, max_length=1000, null=True)),
                ('profilephoto', models.FileField(blank=True, null=True, upload_to='')),
                ('birthday', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('totaltime', models.TextField(blank=True, max_length=1000, null=True)),
                ('place', models.TextField(blank=True, max_length=1000, null=True)),
                ('isitpremium', models.BooleanField(verbose_name='premium')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('Ctgry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
        ),
    ]
