# Generated by Django 3.0.6 on 2020-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200601_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_test', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Yonetim_User',
        ),
    ]
