# Generated by Django 3.0.6 on 2020-07-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200618_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('setcount', models.IntegerField(blank=True, null=True)),
                ('replycount', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('orderlist', models.IntegerField(blank=True, null=True)),
                ('isitduration', models.BooleanField(default=True, verbose_name='isitduration')),
                ('isitrest', models.BooleanField(verbose_name='isitrest')),
                ('video', models.TextField(blank=True, max_length=1000, null=True)),
                ('psc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
