# Generated by Django 3.0.6 on 2020-07-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200701_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programlist',
            old_name='orderlist',
            new_name='resttime',
        ),
        migrations.RemoveField(
            model_name='programlist',
            name='isitrest',
        ),
    ]
