# Generated by Django 3.0.6 on 2020-07-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200702_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlist',
            name='duration',
        ),
    ]
