# Generated by Django 3.0.6 on 2020-07-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_programlist_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='place',
        ),
        migrations.CreateModel(
            name='DietSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('totaltime', models.TextField(blank=True, max_length=1000, null=True)),
                ('isitpremium', models.BooleanField(verbose_name='premium')),
                ('Ctgry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DietProgramlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('kalori', models.IntegerField(blank=True, null=True)),
                ('bfast', models.TextField(blank=True, max_length=1000, null=True)),
                ('afterbfast', models.TextField(blank=True, max_length=1000, null=True)),
                ('lunch', models.TextField(blank=True, max_length=1000, null=True)),
                ('afterlunch', models.TextField(blank=True, max_length=1000, null=True)),
                ('dinner', models.TextField(blank=True, max_length=1000, null=True)),
                ('afterdinner', models.TextField(blank=True, max_length=1000, null=True)),
                ('psc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory')),
            ],
        ),
    ]
