# Generated by Django 3.0.6 on 2020-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200704_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietprogramlist',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
