# Generated by Django 3.0.6 on 2020-07-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_dietprogramlist_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprogramlist',
            name='psc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DietSubCategory'),
        ),
        migrations.AlterField(
            model_name='dietsubcategory',
            name='Ctgry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DietCategory'),
        ),
    ]
