# Generated by Django 3.0.6 on 2020-07-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200705_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlist',
            name='replycount',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programlist',
            name='resttime',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programlist',
            name='setcount',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
