# Generated by Django 3.0.6 on 2020-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200705_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlist',
            name='replycount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programlist',
            name='resttime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programlist',
            name='setcount',
            field=models.IntegerField(default=0),
        ),
    ]
